import Image from 'next/image';

const CustomImage = ({
  src,
  alt,
  title,
  width,
  height,
  ...props
}: {
    src: string;
    alt?: string;
    title?: string;
    width?: string;
    height?: string;
  }): JSX.Element => {
  const match = src.match(/#(\d*)_(\d*)/);
  if (match != null) {
    width ||= match[1];
    height ||= match[2];
  }
  return src.startsWith('/') ? (
    <div className='flex justify-center'>
      <Image {...props} src={src} alt={alt || src} title={title || 'generated by next/image'} width={width || '300'} height={height || '300'} objectFit="contain" />
    </div>
  ) : (
      <img {...props} src={src} alt={alt || src} title={title} width={width || ''} height={height || ''}/>
  );
}

export default CustomImage;